### ISSUE TITLE
Is it convenient for you to provide pre-trained code?

### ISSUE THREAD

**Issue by zhangpeng-HEBUT** [GSidiropoulos/dense-retrieval-against-misspellings#1]
Sorry to bother you, I feel that this paper of yours inspired me a lot, so I went to your github and found the code about this paper, but there is no code about pre-training, can you please send it to me? Thank you!

**Comment by GSidiropoulos** [comment]
Dear Zhang, thank you for your getting in contact. To train our models we followed the original code of DPR (you can find it here: https://github.com/facebookresearch/DPR). Therefore, you can follow the training, encoding, and retrieval steps as described in their repo. In case you want to load one of the pre-trained models we provide I would suggest you clone one of their older branches:

git clone https://github.com/facebookresearch/DPR.git
git checkout 49e5838f94ffced8392be750ded2a8fa4a14b5cf
